dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "file://../loki"
  version: "^2.0.0"
- name: "promtail"
  condition: promtail.enabled
  repository: "file://../promtail"
  version: "^2.0.0"
- name: "grafana"
  condition: grafana.enabled
  version: "~5.7.0"
  repository:  "https://grafana.github.io/helm-charts"
